
services:
  mysql-test:
    image: mysql:8.0
    container_name: melodia-db-test
    env_file:
      - .env.test
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - melodia-test-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 15s

networks:
  melodia-test-network:
    driver: bridge

volumes:
  mysql_test_data:
