import {
  AllSongsResponseSchemaType,
  CreateSongResponseSchemaType,
  SongSchema,
  SongSchemaType,
  SongsResponseSchemaType,
} from '../../schemas/songs';
import { db } from '../db.config';
import logger from '../logger';

/**
 * Creates a new song in the database
 *
 * @param title - The title of the song (required, non-empty string)
 * @param artist - The artist of the song (required, non-empty string)
 * @returns Promise<CreateSongResponseSchemaType> - The created song wrapped in a data object
 * @throws {Error} - If database operation fails
 *
 * @remarks
 * - Both title and artist are trimmed of leading/trailing whitespace
 * - The song ID is auto-generated by the database
 * - Logs the creation of the song for debugging purposes
 *
 * @example
 * ```typescript
 * const songResponse = await createSong("Bohemian Rhapsody", "Queen");
 * console.log(songResponse.data.id); // Auto-generated ID
 * console.log(songResponse.data.title); // "Bohemian Rhapsody"
 * console.log(songResponse.data.artist); // "Queen"
 * ```
 */
export async function createSong(
  title: string,
  artist: string
): Promise<CreateSongResponseSchemaType> {
  let response: CreateSongResponseSchemaType;

  const song = await db.song.create({
    data: {
      title: title.trim(),
      artist: artist.trim(),
    },
  });

  logger.info(`Song created: ${title} by ${artist}`);

  response = {
    data: {
      id: song.id,
      title: song.title,
      artist: song.artist,
    },
  };

  return response;
}

/**
 * Retrieves all songs from the database
 *
 * @returns Promise<SongsResponseSchemaType> - Array of all songs
 * @throws {Error} - If database operation fails
 *
 * @remarks
 * - Returns all songs in the database
 * - Validates each song against the SongSchema
 * - Filters out any songs with invalid data (logs error for invalid songs)
 * - Logs the total number of songs found for debugging
 *
 * @example
 * ```typescript
 * const songs = await getAllSongs();
 * console.log(songs.length); // Total number of songs
 * songs.forEach(song => {
 *   console.log(`${song.title} by ${song.artist}`);
 * });
 * ```
 */
export async function getAllSongs(): Promise<SongsResponseSchemaType> {
  const songs = await db.song.findMany();

  // Convert the result to the correct type
  const validatedSongs = songs
    .map((row: any) => {
      const { success, data, error } = SongSchema.safeParse(row);
      if (!success) {
        logger.error(
          `Invalid song data for song ${JSON.stringify(row)}: ${JSON.stringify(
            error
          )}`
        );
        return null;
      }
      return data;
    })
    .filter(
      (song): song is { title: string; artist: string; id: number } =>
        song !== null
    );

  logger.info(`Songs found: ${JSON.stringify(validatedSongs)}`);
  return validatedSongs;
}
